const P={A:{t:"Día A",p:"A · Fuerza + potencia",d:"Piernas, tracción, empuje y core.",e:[["Salto vertical",3,"3","Potencia","45–60 s"],["Flexión explosiva",3,"3–5","Potencia","45–60 s"],["Sentadilla",3,"4–6","RIR 2","90–120 s"],["Dominadas",3,"5–8","RIR 2","90 s"],["Press banca",3,"5–6","RIR 2","90–120 s"],["Bulgarian split squat",2,"6–8/lado","RIR 2","60–90 s"],["Dead bug + side plank",2,"8/lado + 20–30 s/lado","Core","30–45 s"]]},B:{t:"Día B",p:"B · Cadena posterior + potencia",d:"Cadera, cadena posterior, estabilidad y tracción.",e:[["Salto horizontal",3,"3","Potencia","60 s"],["Kettlebell swing",3,"6–8","Potencia","60 s"],["Peso muerto rumano",3,"5–6","RIR 2","90–120 s"],["Press militar",3,"5–6","RIR 2","90 s"],["Dominadas",3,"5–8","RIR 2","90 s"],["Reverse lunge",2,"6/lado","RIR 2","60–90 s"],["Suitcase carry",2,"20–30 m/lado","Core","45–60 s"]]},C:{t:"Día C",p:"C · Potencia + fuerza relativa",d:"Potencia, fuerza relativa y cadena posterior.",e:[["Jump squat",3,"4","Potencia","45–60 s"],["Flexión explosiva",3,"3–5","Potencia","45–60 s"],["Front squat",3,"4–6","RIR 2","90–120 s"],["Press cerrado",3,"5–6","RIR 2","90 s"],["Dominadas supinas",3,"5–8","RIR 2","90 s"],["Hip thrust",2,"6–8","RIR 2","60–90 s"],["Plancha / shoulder taps",2,"8/lado","Core","30–45 s"]]}};
const T={"Sentadilla":["Pie completo y abdomen firme.","Rodillas siguen los pies; baja con control.","Sube fuerte sin llegar al fallo."],"Dominadas":["Escápulas activas.","Pecho hacia la barra.","Bajada controlada, sin balanceo."],"Press banca":["Escápulas estables y pies firmes.","Barra hacia pecho medio-bajo.","Empuja fuerte sin rebotar."],"Peso muerto rumano":["Cadera atrás, rodillas suaves.","Barra cerca del cuerpo.","Extiende cadera sin perder espalda neutra."],"Press militar":["Glúteos y abdomen firmes.","Barra vertical.","No arquees lumbar."],"Kettlebell swing":["Bisagra de cadera.","Explosión desde la cadera.","Los brazos acompañan; no levantan."],"Bulgarian split squat":["Pierna delantera estable.","Baja controlado.","Empuja el suelo para subir."],"Reverse lunge":["Paso atrás.","Rodilla delantera estable.","Vuelve empujando el suelo."],"Suitcase carry":["Carga en una mano.","Tronco vertical.","Resiste inclinación lateral."],"Front squat":["Codos altos.","Torso erguido.","Si el rack no es seguro, goblet squat."],"Hip thrust":["Espalda alta apoyada.","Extiende cadera.","No hiperextiendas lumbar."],"Press cerrado":["Agarre moderado.","Muñeca neutra.","No fuerces el agarre."],"Dominadas supinas":["Agarre cómodo.","Pecho hacia barra.","Sin balanceo."],"Flexión explosiva":["Cuerpo en bloque.","Baja controlado.","Empuja el suelo rápido."],"Salto vertical":["Semiflexión.","Salta máximo.","Aterriza suave y estable."],"Salto horizontal":["Carga cadera.","Proyecta hacia delante.","Aterriza controlado."],"Jump squat":["Peso corporal o carga mínima.","Salta máximo.","Aterriza suave."],"Plancha / shoulder taps":["Pelvis estable.","Toca hombro contrario.","No rotes el tronco."]};
const K="bstSessionsV2",U="bstProfileV2";let day="A",view="train",tid=null,rem=90,promptInstall=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],hist=()=>{try{return JSON.parse(localStorage.getItem(K)||"[]")}catch{return[]}},put=x=>localStorage.setItem(K,JSON.stringify(x));
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const rest=x=>{let m=x.match(/(\d+)\s*[–-]\s*(\d+)/);return m?Math.round((+m[1]+ +m[2])/2):+(x.match(/\d+/)||[60])[0]};const oneRM=(w,r)=>w*(1+r/30);
function best(n){let b=null;hist().forEach(s=>(s.exercises||[]).forEach(e=>e.name===n&&(e.sets||[]).forEach(x=>{if(x.done&&x.weight&&x.reps&&(!b||x.weight>b.w||(x.weight===b.w&&x.reps>b.r)))b={w:+x.weight,r:+x.reps}})));return b}
function last(n){const h=hist().slice().reverse();for(const s of h)for(const e of s.exercises||[])if(e.name===n){const z=e.sets.filter(x=>x.done&&x.weight>0&&x.reps>0);if(z.length)return z}return[]}
function recommendation(n,r){const l=last(n);if(!l.length)return"Primera vez · usa una carga que permita RIR 2–3";const x=l[0],max=+(String(r).match(/\d+/g)||[0]).at(-1);return x.reps>=max?"Propuesta: +2,5 kg si mantienes RIR 2–3":"Repite "+x.weight+" kg e intenta mejorar 1 repetición"}
function render(){const p=P[day];$("#pill").textContent=p.p;$("#title").textContent=p.t;$("#desc").textContent=p.d;$("#exercises").innerHTML=p.e.map((x,i)=>exercise(x,i)).join("");$$(".tech").forEach(b=>b.onclick=()=>tip(b.dataset.n));$$(".add").forEach(b=>b.onclick=()=>{const c=b.closest(".card").querySelector(".sets"),n=c.children.length;b.before(setHTML(n,parseInt(b.dataset.rest),last(b.dataset.name)[n]||last(b.dataset.name)[0]));bindChecks();});bindChecks();count();$("#coach").textContent=hist().length?("Última sesión: "+(+(hist().at(-1).boxingFeel||3)<=2?"boxeo pesado → hoy reduce 1 serie de accesorios.":"mantén la sesión y prioriza velocidad. ")):"Primera sesión: técnica limpia, RIR 2–3 y máxima calidad en potencia."}
function exercise(x,i){const [n,s,r,f,rt]=x,b=best(n),l=last(n);return '<div class="card exercise"><div class="eh"><div><div class="ename">'+n+'</div><div class="meta">'+s+'×'+r+' · '+f+' · descanso '+rt+'</div><button class="tech" data-n="'+esc(n)+'">ⓘ Técnica</button></div>'+(b?'<span class="best">Mejor '+b.w+'×'+b.r+'</span>':"")+'</div><div class="coach">'+esc(recommendation(n,r))+'</div><div class="sets">'+Array.from({length:s},(_,j)=>setHTML(j,rest(rt),l[j]||l[0])).join("")+'</div><button class="add" data-name="'+esc(n)+'" data-rest="'+rest(rt)+'">+ Añadir serie</button></div>'}
function setHTML(i,rt,prev){return '<div class="set"><span class="setno">'+(i+1)+'</span><label>kg<input class="kg" type="number" step=".5" value="'+(prev?.weight||"")+'"></label><label>reps<input class="rp" type="number" value="'+(prev?.reps||"")+'"></label><label>RIR<select class="ri"><option>3</option><option selected>2</option><option>1</option><option>0</option></select></label><button class="check" data-rest="'+rt+'">✓</button></div>'}
function bindChecks(){$$(".check").forEach(b=>b.onclick=()=>{b.classList.toggle("done");count();if(b.classList.contains("done"))timer(+b.dataset.rest)})}
function count(){const a=$$(".check"),d=$$(".check.done");$("#count").innerHTML=d.length+"/"+a.length+"<br><small>series</small>"}
function collect(){return $$(".exercise").map(c=>({name:c.querySelector(".ename").textContent,sets:[...c.querySelectorAll(".set")].map(r=>({weight:+r.querySelector(".kg").value||0,reps:+r.querySelector(".rp").value||0,rir:+r.querySelector(".ri").value,done:r.querySelector(".check").classList.contains("done")}))}))}
function timer(s){rem=s;$("#timer").classList.remove("hidden");clock();clearInterval(tid);tid=setInterval(()=>{rem--;clock();if(rem<=0){clearInterval(tid);navigator.vibrate?.([150,80,150])}},1000)}
function clock(){$("#time").textContent=String(Math.max(0,rem/60|0)).padStart(2,"0")+":"+String(Math.max(0,rem%60)).padStart(2,"0")}
$("#skip").onclick=()=>{$("#timer").classList.add("hidden");clearInterval(tid)};$("#plus").onclick=()=>{rem+=15;clock()};
function tip(n){const a=T[n]||["Mantén técnica limpia.","Respira y controla el movimiento.","Para si aparece dolor agudo."];$("#modalText").innerHTML="<h2>"+esc(n)+"</h2><ul>"+a.map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul><p class='muted'>Objetivo: terminar normalmente con RIR 2–3, especialmente antes del boxeo.</p>";$("#modal").classList.remove("hidden")}
$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").classList.add("hidden")};
function save(){const ex=collect(),done=ex.flatMap(x=>x.sets).filter(x=>x.done).length;if(!done)return alert("Completa al menos una serie.");const h=hist();h.push({id:Date.now(),date:new Date().toISOString(),day,exercises:ex,rpe:$("#rpe").value,boxingFeel:$("#boxing").value,notes:$("#notes").value.trim()});put(h);$("#notes").value="";$("#rpe").value="";$("#boxing").value="";alert("Sesión guardada.");render()}
function show(v){view=v;["train","progress","history","settings"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==v));$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.v===v));if(v==="progress")progress();if(v==="history")historyUI();if(v==="settings")settingsUI()}
$$(".tab").forEach(b=>b.onclick=()=>show(b.dataset.v));$$(".day").forEach(b=>b.onclick=()=>{day=b.dataset.day;$$(".day").forEach(x=>x.classList.toggle("active",x===b));render()});$("#save").onclick=save;
function progress(){const h=hist(),all=h.flatMap(s=>s.exercises||[]).flatMap(e=>e.sets.filter(x=>x.done&&x.weight>0&&x.reps>0).map(x=>({...x,date:s.date})));const vol=all.reduce((a,x)=>a+x.weight*x.reps,0),avg=h.filter(x=>x.boxingFeel).reduce((a,x)=>a+ +x.boxingFeel,0)/(h.filter(x=>x.boxingFeel).length||1);$("#kpis").innerHTML=[["Sesiones",h.length],["Volumen",(vol/1000).toFixed(1)+" t"],["Ejercicios",new Set(all.map(x=>x.name)).size],["Boxeo medio",h.length?avg.toFixed(1)+"/5":"—"]].map(x=>'<div class="kpi"><b>'+x[1]+'</b><span>'+x[0]+'</span></div>').join("");const names=[...new Set(Object.values(P).flatMap(x=>x.e.map(y=>y[0])))];$("#exercise").innerHTML=names.map(x=>"<option>"+esc(x)+"</option>").join("");$("#exercise").onchange=()=>chartExercise($("#exercise").value);chartExercise(names[0]);boxChart();marks(names)}
function canvas(c,pts,label){const ctx=c.getContext("2d"),W=c.clientWidth,H=c.height;ctx.clearRect(0,0,W,H);ctx.strokeStyle="#e5e7eb";for(let i=0;i<4;i++){let y=15+i*(H-35)/3;ctx.beginPath();ctx.moveTo(30,y);ctx.lineTo(W-10,y);ctx.stroke()}if(!pts.length){ctx.fillStyle="#6b7280";ctx.font="13px system-ui";ctx.fillText("Aún no hay datos suficientes.",30,65);return}const vs=pts.map(x=>x.v),mi=Math.min(...vs),ma=Math.max(...vs),rg=ma-mi||1;ctx.strokeStyle="#2563eb";ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>{let x=30+i*(W-45)/Math.max(1,pts.length-1),y=15+(ma-p.v)/rg*(H-45);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle="#2563eb";pts.forEach((p,i)=>{let x=30+i*(W-45)/Math.max(1,pts.length-1),y=15+(ma-p.v)/rg*(H-45);ctx.beginPath();ctx.arc(x,y,4,0,7);ctx.fill()});ctx.fillStyle="#6b7280";ctx.font="10px system-ui";ctx.fillText(label,30,H-8)}
function chartExercise(n){const pts=[];hist().forEach(s=>(s.exercises||[]).forEach(e=>{if(e.name===n){const z=e.sets.filter(x=>x.done&&x.weight&&x.reps);if(z.length)pts.push({v:+Math.max(...z.map(x=>oneRM(x.weight,x.reps))).toFixed(1)})}}));canvas($("#chart"),pts,"1RM estimado")}
function boxChart(){canvas($("#boxchart"),hist().slice(-8).filter(x=>x.boxingFeel).map(x=>({v:+x.boxingFeel})),"Sensación boxeo · 5 mejor")}
function marks(names){$("#marks").innerHTML="<b>Mejores marcas</b><div class='mark'><b>Ejercicio</b><b>Kg</b><b>Reps</b><b>1RM</b></div>"+names.map(n=>{const b=best(n);return '<div class="mark"><span>'+esc(n)+'</span><span>'+(b?b.w:"—")+'</span><span>'+(b?b.r:"—")+'</span><span>'+(b?oneRM(b.w,b.r).toFixed(1):"—")+'</span></div>'}).join("")}
function historyUI(){const h=hist().slice().reverse();$("#historyList").innerHTML=h.length?h.map(s=>'<div class="history"><button class="delete" data-id="'+s.id+'">Eliminar</button><strong>Día '+s.day+'</strong><small>'+new Date(s.date).toLocaleString("es-ES")+' · RPE '+(s.rpe||"—")+' · Boxeo '+(s.boxingFeel||"—")+'</small><small>'+s.exercises.reduce((a,e)=>a+e.sets.filter(x=>x.done).length,0)+' series · '+Math.round(s.exercises.reduce((a,e)=>a+e.sets.filter(x=>x.done).reduce((q,x)=>q+x.weight*x.reps,0),0))+' kg volumen</small>'+(s.notes?'<p>'+esc(s.notes)+'</p>':"")+'</div>').join(""):'<div class="card muted">No hay sesiones todavía.</div>';$$(".delete").forEach(b=>b.onclick=()=>{if(confirm("¿Eliminar?")){put(hist().filter(x=>String(x.id)!==b.dataset.id));historyUI()}})}
function settingsUI(){let p={};try{p=JSON.parse(localStorage.getItem(U)||"{}")}catch{}$("#name").value=p.name||"";$("#goal").value=p.goal||"performance"}
function exportData(){const x={version:2,exportedAt:new Date().toISOString(),profile:JSON.parse(localStorage.getItem(U)||"{}"),sessions:hist()},a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:"application/json"}));a.download="boxing-strength-"+new Date().toISOString().slice(0,10)+".json";a.click()}
$("#export").onclick=exportData;$("#export2").onclick=exportData;$("#saveSettings").onclick=()=>{localStorage.setItem(U,JSON.stringify({name:$("#name").value.trim(),goal:$("#goal").value}));alert("Guardado")};$("#clear").onclick=()=>{if(confirm("¿Borrar todo?")){localStorage.removeItem(K);localStorage.removeItem(U);show("train");render()}};$("#import").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.sessions))throw 0;put(x.sessions);if(x.profile)localStorage.setItem(U,JSON.stringify(x.profile));alert("Datos importados");progress()}catch{alert("JSON no válido")}};r.readAsText(f)};
addEventListener("beforeinstallprompt",e=>{e.preventDefault();promptInstall=e;$("#install").classList.remove("hidden")});$("#install").onclick=async()=>{if(promptInstall){promptInstall.prompt();promptInstall=null}};if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
render();